title: ACM Blog

baseurl: "/ACM-Blog" # the subpath of your site, e.g. /blog
url: "http://mananagarwal.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  authors:
    output: true
    permalink: /:path/

permalink: /posts/:day-:month-:year/:title/
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
